Add missing pub function to interface
webmatch/WbmTagManagerEcomm pull request #92
Opened 2024-04-16 15:19 UTC by lx-wnk

The public function from the implementing class is missing in the interface.

2024-04-17 05:21 UTC, wbm-sbasler approved these changes

2024-04-17 05:23 UTC, wbm-sbasler requested changes
you should update version in composer.json and add entry in changelog.md.

Please note that we are no longer maintaining this repository.

2024-04-17 07:34 UTC, lx-wnk commented
@wbm-sbasler Thanks for the information - I increased the version and added the changelog entry.

Just so that I get you right - the plugin will still be updated and maintained and this repository is abandoned and no longer maintained?

2024-04-18 05:52 UTC, merged

2024-04-18 05:57 UTC, wbm-sbasler commented
> @wbm-sbasler Thanks for the information - I increased the version and added the changelog entry.
> 
> Just so that I get you right - the plugin will still be updated and maintained and this repository is abandoned and no longer maintained?

Yes, this repository is abandoned and no longer maintained. See first paragraph in [README.md](https://github.com/webmatch/WbmTagManagerEcomm/blob/master/README.md)
There is a successor plugin: https://store.shopware.com/detail/index/sArticle/7813615/number/wbm8772526137131 
We completely gave up plugin maintaining